### ISSUE TITLE
[v2.0.0] Vendure V2 `mysql` migration wrong `SQL` for customFields type:`relation`

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/v2-migration-testbed#7] opened 2023-06-11 11:30 UTC
**Describe the bug**
Vendure V2 `mysql` migration wrong `SQL` for customFields type:`relation`

**To Reproduce**
consider below custom Fields with type: `relation`
```ts
export const productCustomFields: CustomFieldConfig[] = [
 {
    // 当前镜架的镜片流程.
    type: 'relation',
    name: 'lensProcessTemplate',
    nullable: true,
    entity: LensProcessTemplate,
    eager: true,
    public: true,
    label: [
      {
        languageCode: LanguageCode.en,
        value: 'Lens Process Template',
      },
    ],
    description: [
      {
        languageCode: LanguageCode.en,
        value: 'Lens Process Template Configuration',
      },
    ],
  },
]

```
The migration scripts genrated as below

```sql
     await queryRunner.query("ALTER TABLE `product` ADD `customFieldsLensprocesstemplateid` int NULL", undefined);
   
```

before vendure V2,
the `type:relation` it will be translate to `lensProcessTemplateId` for `product` entity.

after upgarde V2:

The type:`relation` will required db schema `customFieldsLensprocesstemplateid` && `lensProcessTemplateId`  at the same time

<img width="729" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/2833251/4454f5bc-528d-490f-b771-ad1001b39eb4">

**Expected behavior**
Should only generated `lensProcessTemplateId` for customFields `type:relation`

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0
 - Nodejs version: 18+
 - Database (mysql/postgres etc):mysql

**Additional context**

**Comment by michaelbromley** [comment] 2023-06-12 14:37
I believe the old behaviour of not prefixing a custom field relation with "customFields" was in fact a bug in TypeORM, reported here:

- https://github.com/typeorm/typeorm/issues/6977

and this got fixed in v0.3.0. Which means it is working "as intended", although I need to add a note to the migration docs for this.

**Comment by tianyingchun** [comment] 2023-07-03 06:30
for above example, it seems that the fields `lensProcessTemplateId` is unneeded

<img width="408" alt="image" src="https://github.com/vendure-ecommerce/v2-migration-tool/assets/2833251/e04a93f2-7ffc-4435-961b-fd50f7b89785">


```ts
{
    // 当前镜架的镜片流程.
    type: 'relation',
    name: 'lensProcessTemplate',
    nullable: true,
    entity: LensProcessTemplate,
    eager: true,
    public: true,
    label: [
      {
        languageCode: LanguageCode.en,
        value: 'Lens Process Template',
      },
    ],
    description: [
      {
        languageCode: LanguageCode.en,
        value: 'Lens Process Template Configuration',
      },
    ],
  },
```
<img width="423" alt="image" src="https://github.com/vendure-ecommerce/v2-migration-tool/assets/2833251/c38be253-9c58-4f11-ba11-f99c6550871d">

the fields `lensProcessTemplateId` of `product` table is no responsible changed while we update `lensProcessTemplate`

but the migration always ask me need to add coloumns `lensProcessTemplateId`, `customFieldsLensprocesstemplateid` at the same times.

**Comment by tianyingchun** [comment] 2023-07-03 06:38
it seems that we need to remove fields `lensProcessTemplateId` from table schema? but `vendure` ask we need to add this field?

**Comment by tianyingchun** [comment] 2023-07-03 08:37
after i run `yarn  migration` it always ask me to run 

```ts
    await queryRunner.query("ALTER TABLE `product` ADD `lensProcessTemplateId` int NULL", undefined);
        await queryRunner.query("ALTER TABLE `product` ADD CONSTRAINT `FK_ae3160ca60b45af225917e84e4c` FOREIGN KEY (`customFieldsLensprocesstemplateid`) REFERENCES `lens_process_template`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
```

**Comment by tianyingchun** [comment] 2023-07-06 05:18
below example with `type:relation` it is right?
```ts
{
  
    type: 'relation',
    name: 'campaign',
    nullable: true,
    entity: Campaign,
...
}
```
```ts

await queryRunner.query(
  "ALTER TABLE `collection` RENAME COLUMN `campaignId` TO `customFieldsCampaignid`",
  undefined
);
await queryRunner.query("ALTER TABLE `collection` ADD `campaignId` int NULL", undefined);

```
 
after rename  type: `entity`, https://github.com/vendure-ecommerce/v2-migration-tool/commit/b59607abf6efbc76571283aa76c6c38111b44ff5

the migration scripts also need to add `entityXXXId` back

**Comment by tianyingchun** [comment] 2023-07-17 01:42
2.0.4 it works correct migration successfully!

**Closed as completed** 2023-07-17 01:42 UTC
